# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_modular_headers!
use_frameworks!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end

target 'VideoChat' do
  pod 'SlackTextViewController'
  pod 'SDWebImage'
  pod 'TTTAttributedLabel'
  pod 'StraaS-iOS-SDK', :path=>'../'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManager'
  pod 'Socket.IO-Client-Swift', '~> 15.1.0'
  pod 'IJKMediaFramework', '~> 0.1.2'
end
